version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
    # 1
    # fgsl
    # gtkextra
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: false
      RNG: fgsl
      PLOT: gtkextra
    # 2
    # fgsl
    # gtkextra
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: true
      RNG: fgsl
      PLOT: gtkextra
    # 3
    # fgsl
    # gtkmm-plplot
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: false
      RNG: fgsl
      PLOT: gtkmm-plplot
    # 4
    # fgsl
    # gtkmm-plplot
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: true
      RNG: fgsl
      PLOT: gtkmm-plplot
    # 5
    # fgsl
    # no gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      RNG: fgsl
    # 6
    # easyRNG
    # gtkextra
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: false
      RNG: easyRNG
      PLOT: gtkextra
    # 7
    # easyRNG
    # gtkextra
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: true
      RNG: easyRNG
      PLOT: gtkextra
    # 8
    # easyRNG
    # gtkmm-plplot
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: false
      RNG: easyRNG
      PLOT: gtkmm-plplot
    # 9
    # easyRNG
    # gtkmm-plplot
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: true
      RNG: easyRNG
      PLOT: gtkmm-plplot
    # 
    # easyRNG
    # gtkmm-plplot
    # with updater
    # with gui
    # with google analytics
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      UPDATER: true
      RNG: easyRNG
      PLOT: gtkmm-plplot
      GOOGLE_ANALYTICS: true
    # 10
    # easyRNG
    # no gui
    - compiler: msvc_msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      RNG: easyRNG
#    - compiler: msvc_msys2
#      ARCH: x86
#      MSYS2_ARCH: i686
#      MSYS2_DIR: msys64
#      MSYSTEM: MINGW32
    # 11
    # fgsl
    # gtkextra
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: false
      RNG: fgsl
      PLOT: gtkextra
    # 12
    # fgsl
    # gtkextra
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: true
      RNG: fgsl
      PLOT: gtkextra
    # 13
    # fgsl
    # gtkmm-plplot
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: false
      RNG: fgsl
      PLOT: gtkmm-plplot
    # 14
    # fgsl
    # gtkmm-plplot
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: true
      RNG: fgsl
      PLOT: gtkmm-plplot
    # 15
    # fgsl
    # no gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      RNG: fgsl
    # 16
    # easyRNG
    # gtkextra
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: false
      RNG: easyRNG
      PLOT: gtkextra
    # 17
    # easyRNG
    # gtkextra
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: true
      RNG: easyRNG
      PLOT: gtkextra
    # 18
    # easyRNG
    # gtkmm-plplot
    # no updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: false
      RNG: easyRNG
      PLOT: gtkmm-plplot
    # 19
    # easyRNG
    # gtkmm-plplot
    # with updater
    # with gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      UPDATER: true
      RNG: easyRNG
      PLOT: gtkmm-plplot
    # 20
    # easyRNG
    # no gui
    - compiler: msvc_msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      RNG: easyRNG

before_build:
    - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%
    - bash -lc "for i in {1..3}; do pacman -Syyuu --noconfirm && break || sleep 15; done"
    - bash -lc "for i in {1..3}; do pacman -Suu --noconfirm && break || sleep 15; done"
    - bash -lc "for i in {1..3}; do pacman --noconfirm -Su mingw-w64-%MSYS2_ARCH%-{gcc,libtool,curl,gcc-fortran,libxslt,glib2} automake autoconf make wget tar && break || sleep 15; done"
    - bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./appveyor-before-build.sh"

build_script:
    - bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./appveyor-build-script.sh"

branches:
  only:
    - master

