
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __XMIMSIM_TYPE_BUILTINS_H__
#define __XMIMSIM_TYPE_BUILTINS_H__

#include <glib-object.h>
#include <glib.h>

G_BEGIN_DECLS
/* enumerations from "../include/xmi_job.h" */
GType xmi_msim_job_error_get_type (void);
#define XMI_MSIM_TYPE_JOB_ERROR (xmi_msim_job_error_get_type())
GType xmi_msim_job_special_event_get_type (void);
#define XMI_MSIM_TYPE_JOB_SPECIAL_EVENT (xmi_msim_job_special_event_get_type())

G_END_DECLS
#endif /* __XMIMSIM_TYPE_BUILTINS_H__ */

/* Generated data ends here */

