
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "xmi_type_builtins.h"
#include "xmi_job.h"

/* enumerations from "../include/xmi_job.h" */
GType
xmi_msim_job_error_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { XMI_MSIM_JOB_ERROR_INVALID_INPUT, "XMI_MSIM_JOB_ERROR_INVALID_INPUT", "invalid-input" },
      { XMI_MSIM_JOB_ERROR_UNAVAILABLE, "XMI_MSIM_JOB_ERROR_UNAVAILABLE", "unavailable" },
      { XMI_MSIM_JOB_ERROR_ANOTHER_JOB_RUNNING, "XMI_MSIM_JOB_ERROR_ANOTHER_JOB_RUNNING", "another-job-running" },
      { XMI_MSIM_JOB_ERROR_HDF5, "XMI_MSIM_JOB_ERROR_HDF5", "hdf5" },
      { XMI_MSIM_JOB_ERROR_PROCESS, "XMI_MSIM_JOB_ERROR_PROCESS", "process" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static(g_intern_static_string("XmiMsimJobError"), values);
  }
  return etype;
}
GType
xmi_msim_job_special_event_get_type (void)
{
  static GType etype = 0;
  if (etype == 0) {
    static const GEnumValue values[] = {
      { XMI_MSIM_JOB_SPECIAL_EVENT_SOLID_ANGLE, "XMI_MSIM_JOB_SPECIAL_EVENT_SOLID_ANGLE", "solid-angle" },
      { XMI_MSIM_JOB_SPECIAL_EVENT_SIMULATION, "XMI_MSIM_JOB_SPECIAL_EVENT_SIMULATION", "simulation" },
      { XMI_MSIM_JOB_SPECIAL_EVENT_ESCAPE_PEAKS, "XMI_MSIM_JOB_SPECIAL_EVENT_ESCAPE_PEAKS", "escape-peaks" },
      { 0, NULL, NULL }
    };
    etype = g_enum_register_static(g_intern_static_string("XmiMsimJobSpecialEvent"), values);
  }
  return etype;
}

/* Generated data ends here */

